services:
  app:
    build:
      args:
        USER: user
        USER_ID: 1000
        GROUP_ID: 1000
      context: docker/php
      dockerfile: Dockerfile
    container_name: codebase-app
    restart: unless-stopped
    working_dir: /app
    environment:
      XDEBUG_CONFIG: "client_host=172.29.48.1 idekey==PHPSTORM client_port=9004 mode=debug"
      PHP_IDE_CONFIG: "serverName=codebase-app"
    volumes:
      - ./:/app
    networks:
      - codebase-network

  db:
    image: mysql:8.0.32
    container_name: codebase-mysql
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "13306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: codebase
      MYSQL_DATABASE: codebase
      MYSQL_USER: codebase
      MYSQL_PASSWORD: codebase
    networks:
      - codebase-network

  nginx:
    image: nginx:latest
    container_name: codebase-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      codebase-network:
        aliases:
          - codebase.localhost
    depends_on:
      - app

  redis:
    container_name: codebase-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - codebase-network

networks:
  codebase-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.16/28

volumes:
  pg_data:
    driver: local
